version: '3'
services:
  back:
    build:
      context: .
    container_name: dodream-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - TZ=Asia/Seoul
    networks:
      - dodream-net
    restart: always
networks:
  dodream-net:
    driver: bridge
