spring:
  application:
    name: test-dodream-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: Minsung1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
  sql:
    init:
      mode: never
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  issuer: kosta-inkyu
  secret_key: mysecretmysecretmysecretmysecret
  access_duration: 1800000      # 1800000  # 30분 (30 * 60 * 1000)
  refresh_duration: 86400000    # 86400000 # 24시간 (24 * 60 * 60 * 1000)

oauth2:
  clients:
    google:
      client-id:
      client-secret:
      redirect-uri:
      token-uri:
      user-info-request-uri:
    kakao:
      client-id:
      client-secret:
      redirect-uri:
      token-uri:
      user-info-request-uri:
    naver:
      client-id:
      client-secret:
      redirect-uri:
      token-uri:
      user-info-request-uri: